add_newline = false

[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âžŸ"
# [character]      # The name of the module we are configuring is "character"
use_symbol_for_status = true
symbol = "  â¯"     # The "symbol" segment is being set to "âžœ"
error_symbol = "  âœ—"
style_success = "bold #00A652"
style_failure = "bold #df382c"

[git_branch]
symbol = 'branch '
truncation_length = 4
truncation_symbol = ''

[git_status]
conflicted = 'p '
ahead = 'ahead '
behind = 'ðŸ˜° '
diverged = 'ðŸ˜µ '
up_to_date = ' âœ“ '
untracked = 'untracked'
stashed = 'stashed'
modified = 'modified'
staged = '[++\($count\)](green)'
renamed = 'renamed'
deleted = 'deleted'

# ~/.config/starship.toml

[sudo]
style = 'bold italic green'
symbol = 'sudo '
disabled = true

# [username]
# style_user = 'bold italic green'
# style_root = 'black bold'
# format = '[$user]($style) '
# disabled = false
# show_always = true

# shows the hostname on new lines
[hostname]
ssh_only = false
# prefix = "ðŸ’»ï¸ "
# suffix = ">>"
trim_at = ".companyname.com"
disabled = true
style = "bold italic #87A752"

# configure directory
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
